language: php

php:
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install:
  - composer i

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache
